source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'IronSourceAdColonyAdapter', '4.3.3.1'
  pod 'IronSourceAdMobAdapter', '4.3.16.0'
  pod 'IronSourceAmazonAdapter', '4.3.4.6'
  pod 'IronSourceAppLovinAdapter', '4.3.18.0'
  pod 'IronSourceChartboostAdapter', '4.3.4.0'
  pod 'IronSourceFacebookAdapter', '4.3.18.5'
  pod 'IronSourceFyberAdapter', '4.3.9.0'
  pod 'IronSourceHyprMXAdapter', '4.1.6.5'
  pod 'IronSourceInMobiAdapter', '4.3.7.5'
  pod 'IronSourceMaioAdapter', '4.1.7.0'
  pod 'IronSourcePangleAdapter', '4.1.7.0'
  pod 'IronSourceSDK', '7.0.1.0'
  pod 'IronSourceTapjoyAdapter', '4.1.13.1'
  pod 'IronSourceUnityAdsAdapter', '4.3.4.2'
  pod 'IronSourceVungleAdapter', '4.3.5.0'
end
